version: "3.3"

services:
  node:
    container_name: fenzo-react
    restart: always
    image: node:20.10.0
    expose:
      - "4002"
    environment:
      - PORT=4002
    volumes:
      - ./:/usr/src/fenzo-react
    working_dir: /usr/src/fenzo-react
    networks:
      - web
    command: bash -c "yarn global add serve && yarn install --check-files && node node_modules/react-scripts/bin/react-scripts.js build && serve -s build -l 4002"

networks:
  web:
    external: true
    name: web
